version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: empanadas_postgres
    restart: always
    environment:
      POSTGRES_DB: empanadas_db
      POSTGRES_USER: empanadas_user
      POSTGRES_PASSWORD: empanadas_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
